GET http://localhost:8080/api/types/Skateboard/skateboards

###

GET http://localhost:8080/api/types/Skateboard/skateboards/3

###

GET http://localhost:8080/api/types/Longboard/skateboards

###

GET http://localhost:8080/api/types/Penny/skateboards/6

###

GET http://localhost:8080/api/types/Longboard/skateboards/1

###


GET http://localhost:8080/api/types

###

GET http://localhost:8080/api/types/Longboard

###

GET http://localhost:8080/api/types/Skateboard

###

GET http://localhost:8080/api/types/Scooter

###

GET http://localhost:8080//api/types/Penny

###

GET http://localhost:8080/api/types/Cruiser

###

GET http://localhost:8080/api/types/Electroboard

###

POST http://localhost:8080/api/types
Content-Type: application/json

{
  "typeName": "Electroboard",
  "avgSpeed": 50.0,
  "maxWeight": 140
}

###

POST http://localhost:8080/api/types
Content-Type: application/json

{
  "typeName": "Electroboard",
  "avgSpeed": "a50.0",
  "maxWeight": 140
}

###
PUT http://localhost:8080/api/types/Electroboard
Content-Type: application/json

{
  "avgSpeed": 40.0,
  "maxWeight": 160
}

###
PUT http://localhost:8080/api/types/Howerboard
Content-Type: application/json

{
  "avgSpeed": 63.0,
  "maxWeight": 80
}

###

DELETE http://localhost:8080/api/types/Longboard

###

DELETE http://localhost:8080/api/types/Howerboard

###

POST http://localhost:8082/api/types/Skateboard/skateboards
Content-Type: application/json

{
  "name": "TestSkateboard",
  "producer": "TestProducer",
  "price": 90.0
}

###

DELETE http://localhost:8082/api/types/Longboard/skateboards/8

###

PUT http://localhost:8082/api/types/Longboard/skateboards/8
Content-Type: application/json

{
  "name": "UpdatedTestSkateboard",
  "producer": "UpdatedTestProducer",
  "price": 40.0
}

###

GET http://localhost:8082/api/types/Longboard/skateboards/8

###
